# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  routing_loader:
    include_format: false
  view:
    view_response_listener: true
  format_listener:
    rules:
      - { path: '^/', priorities: ['json'], fallback_format: 'json', prefer_extension: false }
  body_listener:
    enabled: false